# Documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/
# dependabot-version-updates/customizing-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
